/**
 * Especialidades médicas disponíveis para cadastro e busca.
 * Manter em ordem alfabética para facilitar scan pelo usuário.
 * Deve ser a ÚNICA fonte de verdade — tanto o cadastro (CadastroMedico)
 * quanto o filtro de busca do paciente (Consulta.tsx) devem consultar daqui.
 */
export const ESPECIALIDADES_MEDICAS = [
  "Acupuntura",
  "Alergia e Imunologia",
  "Anestesiologia",
  "Angiologia",
  "Cardiologia",
  "Cirurgia Cardiovascular",
  "Cirurgia Geral",
  "Cirurgia Pediátrica",
  "Cirurgia Plástica",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Clínica Médica",
  "Coloproctologia",
  "Dermatologia",
  "Endocrinologia",
  "Endocrinologia Pediátrica",
  "Gastroenterologia",
  "Genética Médica",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia",
  "Hepatologia",
  "Homeopatia",
  "Infectologia",
  "Mastologia",
  "Medicina de Família e Comunidade",
  "Medicina do Esporte",
  "Medicina do Trabalho",
  "Medicina Esportiva",
  "Medicina Estética",
  "Medicina Intensiva",
  "Medicina Interna",
  "Medicina Legal",
  "Medicina Nuclear",
  "Medicina Preventiva",
  "Nefrologia",
  "Neurocirurgia",
  "Neurologia",
  "Nutrologia",
  "Oftalmologia",
  "Oncologia",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Patologia",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Radiologia",
  "Radioterapia",
  "Reumatologia",
  "Urologia",
] as const;

export const UFS = [
  { value: "AC", label: "AC" }, { value: "AL", label: "AL" },
  { value: "AP", label: "AP" }, { value: "AM", label: "AM" },
  { value: "BA", label: "BA" }, { value: "CE", label: "CE" },
  { value: "DF", label: "DF" }, { value: "ES", label: "ES" },
  { value: "GO", label: "GO" }, { value: "MA", label: "MA" },
  { value: "MT", label: "MT" }, { value: "MS", label: "MS" },
  { value: "MG", label: "MG" }, { value: "PA", label: "PA" },
  { value: "PB", label: "PB" }, { value: "PR", label: "PR" },
  { value: "PE", label: "PE" }, { value: "PI", label: "PI" },
  { value: "RJ", label: "RJ" }, { value: "RN", label: "RN" },
  { value: "RS", label: "RS" }, { value: "RO", label: "RO" },
  { value: "RR", label: "RR" }, { value: "SC", label: "SC" },
  { value: "SP", label: "SP" }, { value: "SE", label: "SE" },
  { value: "TO", label: "TO" },
] as const;

export const TIPOS_CONSELHO = [
  { value: "CRM", label: "CRM (Medicina)" },
  { value: "CRO", label: "CRO (Odontologia)" },
  { value: "CREFITO", label: "CREFITO (Fisioterapia)" },
  { value: "CRN", label: "CRN (Nutrição)" },
  { value: "CRP", label: "CRP (Psicologia)" },
  { value: "CRF", label: "CRF (Farmácia)" },
  { value: "CRFa", label: "CRFa (Fonoaudiologia)" },
  { value: "COREN", label: "COREN (Enfermagem)" },
  { value: "CRBM", label: "CRBM (Biomedicina)" },
  { value: "OUTRO", label: "Outro" },
] as const;
